### ISSUE TITLE
Folder dropping doesn't work

### ISSUE THREAD

**Issue by kwhitefoot** [schollz/hostyoself#5]
I dropped a folder and the list of files served was correct but navigating to the charmingly named url returned a 404 response.

Worked perfectly for a single file from the same folder.

How does this work?  Does all the traffic go through your server?  If so, surely it will cost you a fortune in bandwidth charges if anyone seriously uses the idea.

Anyway, it's a cool demo.

Edit: forgot to mention that I'm running Firefox 67.0.4, 64 bit, on Windows 10.

**Comment by schollz** [comment]
Thanks, I was seeing this too, sometimes... I think I fixed it with https://github.com/schollz/hostyoself/commit/3520f36f721bba96bdb95b53f2b9ca4b6c473b48.

Try Force-reload your browser to update your browser and try again! (Ctl + F5)

**Comment by schollz** [comment]
Also, I should mention because this is non-obvious. If you drop a folder and there is no `index.html` then it will refuse to serve any file. When you drop a folder you have to specify the filepath for it to serve the right file (unless there is a `index.html` in which case it will serve, just like a webserver does).

**Comment by kwhitefoot** [comment]
>  no index.html then it will refuse to serve any file.
Ah, so it doesn't list the directory.  I was expecting it to work the same way as the browser does when given a local file url.

**Comment by schollz** [comment]
That could be a cool feature!

**Comment by schollz** [comment]
@kwhitefoot I added this feature :)
